extends Node2D

const iso_639_2_language_endonyms = {
	"aar": "Qafaraf; ’Afar Af; Afaraf; Qafar af",
	"abk": "Аҧсуа бызшәа; Аҧсшәа",
	"ace": "Basa Acèh,بهسا اچيه",
	"ach": "Lwo",
	"ada": "Dangme",
	"ady": "Адыгабзэ; Кӏахыбзэ",
	"afa": "",
	"afh": "El-Afrihili",
	"afr": "Afrikaans",
	"ain": "Aynu=itak, アイヌ・イタㇰ",
	"aka": "Akan",
	"akk": "𒀝𒅗𒁺𒌑",
	"alb": "Shqip",
	"ale": "Унáӈам тунуý; Унаӈан умсуу",
	"alg": "",
	"alt": "Алтай тили",
	"amh": "አማርኛ",
	"ang": "Ænglisc; Anglisc; Englisc",
	"anp": "",
	"apa": "",
	"ara": "العربية",
	"arc": "",
	"arg": "aragonés",
	"arm": "Հայերէն; Հայերեն",
	"arn": "(mapuθuŋun)",
	"arp": "Hinónoʼeitíít",
	"art": "",
	"arw": "Lokono",
	"asm": "অসমীয়া",
	"ast": "Asturianu",
	"ath": "",
	"aus": "",
	"ava": "Магӏарул мацӏ; Авар мацӏ",
	"ave": "",
	"awa": "अवधी",
	"aym": "Aymar aru",
	"aze": "Azərbaycan dili; Азәрбајҹан дили; آذربایجان دیلی",
	"bad": "",
	"bai": "Bamiléké",
	"bak": "Башҡорт теле; Başqort tele",
	"bal": "بلوچی",
	"bam": "ߓߊߡߊߣߊߣߞߊߣ",
	"ban": "ᬪᬵᬱᬩᬮᬶ; ᬩᬲᬩᬮᬶ",
	"baq": "euskara",
	"bas": "Mbene; Ɓasaá",
	"bat": "",
	"bej": "Bidhaawyeet",
	"bel": "Беларуская мова",
	"bem": "Chibemba",
	"ben": "বাংলা",
	"ber": "Tamaziɣt; Tamazight; ⵜⴰⵎⴰⵣⵉⵖⵜ; ⵝⴰⵎⴰⵣⵉⵗⵝ; ⵜⴰⵎⴰⵣⵉⵗⵜ",
	"bho": "भोजपुरी",
	"bih": "",
	"bik": "",
	"bin": "Ẹ̀dó",
	"bis": "",
	"bla": "ᓱᖽᐧᖿ",
	"bnt": "",
	"bod": "བོད་སྐད་; ལྷ་སའི་སྐད་",
	"bos": "bosanski; босански",
	"bra": "",
	"bre": "Brezhoneg",
	"btk": "",
	"bua": "буряад хэлэн",
	"bug": "ᨅᨔ ᨕᨘᨁᨗ",
	"bul": "български език",
	"bur": "မြန်မာစာ; မြန်မာစကား",
	"byn": "ብሊና, ብሊን",
	"cad": "Hasí:nay",
	"cai": "",
	"car": "Kari'nja",
	"cat": "català",
	"cau": "",
	"ceb": "Sinugbuanong Binisayâ",
	"cel": "",
	"ces": "čeština; český jazyk",
	"cha": "Finu' Chamoru",
	"chb": "Muysccubun",
	"che": "Нохчийн мотт; ნახჩიე მუოთთ; نَاخچیین موٓتت",
	"chg": "جغتای",
	"chi": "中文; 汉语; 漢語",
	"chk": "",
	"chm": "марий йылме",
	"chn": "chinuk wawa; wawa; chinook lelang; lelang",
	"cho": "Chahta'",
	"chp": "ᑌᓀᓱᒼᕄᓀ (Dënesųłiné)",
	"chr": "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ",
	"chu": "Славе́нскїй ѧ҆зы́къ",
	"chv": "Чӑвашла",
	"chy": "Tsėhésenėstsestȯtse",
	"cmc": "",
	"cnr": "crnogorski, црногорски",
	"cop": "t.mənt.rəm.ən.kēme",
	"cor": "Kernowek",
	"cos": "Corsu; Lingua corsa",
	"cpe": "",
	"cpf": "",
	"cpp": "",
	"cre": "Nēhiyawēwin, ᓀᐦᐃᔭᐍᐏᐣ",
	"crh": "Къырымтатарджа; Къырымтатар тили; Ҡырымтатарҗа; Ҡырымтатар тили",
	"crp": "",
	"csb": "Kaszëbsczi jãzëk",
	"cus": "",
	"cym": "Cymraeg; y Gymraeg",
	"cze": "čeština; český jazyk",
	"dak": "Dakhótiyapi; Dakȟótiyapi",
	"dan": "dansk",
	"dar": "дарган мез",
	"day": "",
	"del": "",
	"den": "Dene K'e",
	"deu": "Deutsch",
	"dgr": "Tłįchǫ Yatiì",
	"din": "Thuɔŋjäŋ",
	"div": "ދިވެހި; ދިވެހިބަސް",
	"doi": "डोगरी;ڈوگرى",
	"dra": "",
	"dsb": "Dolnoserbski; Dolnoserbšćina",
	"dua": "",
	"dum": "",
	"dut": "Nederlands; Vlaams",
	"dyu": "Julakan",
	"dzo": "རྫོང་ཁ་",
	"efi": "",
	"egy": "",
	"eka": "",
	"ell": "Νέα Ελληνικά",
	"elx": "",
	"eng": "English",
	"enm": "",
	"epo": "Esperanto",
	"est": "eesti keel",
	"eus": "euskara",
	"ewe": "Èʋegbe",
	"ewo": "",
	"fan": "Faŋ, Paŋwe",
	"fao": "føroyskt",
	"fas": "فارسی",
	"fat": "Mfantse; Fante; Fanti",
	"fij": "Na Vosa Vakaviti",
	"fil": "Wikang Filipino",
	"fin": "suomen kieli",
	"fiu": "",
	"fon": "fɔ̀ngbè",
	"fra": "français",
	"frm": "françois; franceis",
	"fro": "Franceis; François; Romanz",
	"frr": "Frasch; Fresk; Freesk; Friisk",
	"frs": "Seeltersk",
	"fry": "Frysk",
	"ful": "Fulfulde; Pulaar; Pular",
	"fur": "Furlan",
	"gaa": "Gã",
	"gay": "Basa Gayo",
	"gba": "",
	"gem": "",
	"geo": "ქართული",
	"ger": "Deutsch",
	"gez": "ግዕዝ",
	"gil": "Taetae ni Kiribati",
	"gla": "Gàidhlig",
	"gle": "Gaeilge",
	"glg": "galego",
	"glv": "Gaelg; Gailck",
	"gmh": "Diutsch",
	"goh": "Diutisk",
	"gon": "गोंडी",
	"gor": "Bahasa Hulontalo",
	"got": "",
	"grb": "",
	"grc": "Ἑλληνική",
	"gre": "Νέα Ελληνικά",
	"grn": "Avañe'ẽ",
	"gsw": "Schwiizerdütsch",
	"guj": "ગુજરાતી",
	"gwi": "Dinjii Zhu’ Ginjik",
	"hai": "X̱aat Kíl; X̱aadas Kíl; X̱aayda Kil; Xaad kil",
	"hat": "kreyòl ayisyen",
	"hau": "Harshen Hausa;هَرْشَن",
	"haw": "ʻŌlelo Hawaiʻi",
	"heb": "עברית",
	"her": "Otjiherero",
	"hil": "Ilonggo",
	"him": "पश्चिमी पहाड़ी, हिमाचली",
	"hin": "हिन्दी",
	"hit": "𒉈𒅆𒇷",
	"hmn": "lus Hmoob; lug Moob; lol Hmongb",
	"hmo": "",
	"hrv": "hrvatski",
	"hsb": "hornjoserbšćina",
	"hun": "magyar nyelv",
	"hup": "Na:tinixwe Mixine:whe'",
	"hye": "Հայերէն; Հայերեն",
	"iba": "Jaku Iban",
	"ibo": "Asụsụ Igbo",
	"ice": "íslenska",
	"ido": "",
	"iii": "ꆈꌠꉙ",
	"ijo": "Ịjọ",
	"iku": "ᐃᓄᒃᑎᑐᑦ",
	"ile": "",
	"ilo": "Pagsasao nga Ilokano; Ilokano",
	"ina": "",
	"inc": "",
	"inh": "ГӀалгӀай мотт",
	"ipk": "Iñupiaq",
	"ira": "",
	"iro": "",
	"isl": "íslenska",
	"ita": "italiano; lingua italiana",
	"jav": "ꦧꦱꦗꦮ",
	"jbo": "la .lojban.",
	"jpn": "日本語",
	"jpr": "Dzhidi",
	"jrb": "عربية يهودية, ערבית יהודית",
	"kaa": "Qaraqalpaq tili; Қарақалпақ тили",
	"kab": "ⵜⴰⵇⴱⴰⵢⵍⵉⵜ Taqbaylit, d=al-lughat al-qabāʾilīya, اللغة القبائلية",
	"kac": "景颇语",
	"kal": "",
	"kam": "",
	"kan": "ಕನ್ನಡ",
	"kar": "",
	"kas": "कश्मीरी,كشميري",
	"kat": "ქართული",
	"kau": "",
	"kaw": "ꦧꦱꦗꦮ",
	"kaz": "қазақ тілі, qazaq tili",
	"kbd": "Адыгэбзэ (Къэбэрдейбзэ)",
	"kha": "কা কতিয়েন খাশি",
	"khi": "",
	"khm": "ភាសាខ្មែរ",
	"kho": "",
	"kik": "Gĩkũyũ",
	"kin": "Ikinyarwanda",
	"kir": "Кыргыз тили; Киргиз тили",
	"kmb": "Kikongo",
	"kok": "कोंकणी; Konknni",
	"kom": "коми кыв; кoмий кыv",
	"kon": "KiKongo",
	"kor": "한국어",
	"kos": "Kosraean",
	"kpe": "Kpɛlɛɛ; Kpele",
	"krc": "къарачай-малкъар; къарачай малкъар; къарачай-малкъар тил",
	"krl": "karjalan kieli; karjal; kariela kieli",
	"kro": "Nupe; Kro",
	"kru": "કોંકણી; koṅkaṇī",
	"kua": "Kuanyama; Rukwangali; Rukwangali; Rungwangali; Kwanyama",
	"kum": "къумукъ тил; къумукъ чIов",
	"kur": "Kurdî; كوردی; کوردی",
	"kut": "Ktunaxa",
	"lad": "לאדינו",
	"lah": "لاهناے",
	"lam": "",
	"lao": "ພາສາລາວ",
	"lat": "Lingua Latina",
	"lav": "Latviešu Valoda",
	"lez": "Лезги чIал; Лезги чIал лезгийн; Лезги лезги",
	"lim": "Lèmburgs; Límboergs; Limburger; Limburgs",
	"lin": "Lingála; Nɔ́ngála",
	"lit": "Lietuvių Kalba",
	"lol": "Te Tunga",
	"loz": "Silozi; Rozi; Rotse",
	"ltz": "Lëtzebuergesch; Luxemburgisch; Luxembourgeois",
	"lua": "Kiluba",
	"lub": "Tshiluba",
	"lug": "Oluganda",
	"lui": "",
	"lun": "chiLunda; chilunda; silunda; siluba",
	"luo": "Dholuo",
	"lus": "Mizo ţawng",
	"mac": "македонски јазик",
	"mad": "Madhurèh",
	"mag": "मगही",
	"mah": "Kajin M̧ajeļ",
	"mai": "मैथिली",
	"mak": "Makaa",
	"mal": "മലയാളം",
	"man": "",
	"mao": "Te reo Māori",
	"map": "Bahasa Malaysia",
	"mar": "मराठी",
	"mas": "Ekegusii; Gusii",
	"may": "Bahasa Melayu",
	"mdf": "коми кыв; кoмий кыv",
	"mdr": "Moksha",
	"men": "Олык марий; Марий",
	"mga": "Gaeilge",
	"mic": "ᒥᓯᓇᐃᑦ",
	"min": "Bahaso Minangkabau; Baso Minang; Baso Padang",
	"mis": "",
	"mkh": "",
	"mlg": "fiteny malagasy; malagasy",
	"mlt": "Malti",
	"mnc": "满洲語; manju gisun",
	"mni": "মৈতৈ; Meiteilon; Meithei; Meetei; Meithe; Meeteilon; Meiteiron",
	"mno": "",
	"moh": "Kanien'kéha",
	"mon": "Монгол; Монгол хэл; ᠮᠣᠨᠭᠣᠯ ᠬᠡᠯᠡ",
	"mos": "Kílêmbe; Kílume; Kílεngε; Kímusanga",
	"mul": "",
	"mun": "",
	"mus": "Mvskoke; Muscogee; Creek",
	"mwl": "Mirandês",
	"mwr": "मारवाङ; مارواری",
	"myn": "",
	"myv": "эрзянь кель; эрзянь кельн; эрзякс; эрзякс кель; эрзянь; эрзянь кельтн",
	"nah": "Nāhuatl; Nāhuatl tlahtōlli; Mexicatl tlahtōlli",
	"nai": "",
	"nap": "Napulitano",
	"nau": "Ekakairũ Naoero",
	"nav": "Diné bizaad; Dinékʼehǰí",
	"nbl": "isiNdebele",
	"nde": "isiNdebele",
	"ndo": "Owambo",
	"nds": "Plattdüütsch; Plattdeutsch; Plattduitsch; Nedderdüütsch",
	"nep": "नेपाली",
	"new": "नेपालभाषा, नेपाली",
	"nia": "Li Niha",
	"nic": "",
	"niu": "Faka Tonga",
	"nld": "Nederlands; Vlaams",
	"nno": "Norsk Nynorsk",
	"nob": "Norsk Bokmål",
	"nog": "Ногай тили; Noğay tili",
	"non": "Norrœnt mál",
	"nor": "Norsk",
	"nqo": "ߒߞߏߞߐߛߌߟߌ; ߞߏߝߌߛߊߖߌ; ߡߐߙ߇ߙߐߘߊ; ߡߏߣߎߝߏߘߏ; ߡߙߎߛߏ; ߡߙߏߣߘߏ",
	"nso": "Sesotho sa Leboa",
	"nub": "",
	"nwc": "नेपालभाषा, नेपाली",
	"nya": "ChiCheŵa; Chinyanja",
	"nym": "Nyamwezi; Nyamwezi kiSwahili",
	"nyn": "Runyankore; Ikinyarwanda; Nyankore",
	"nyo": "Nyankole; Chinyankore",
	"nzi": "Nzima",
	"oci": "occitan; lenga d'òc; lenga d'òc (gascon)",
	"oji": "ᐊᓂᔑᓈᐯ; Anishinaabemowin; Ojibwemowin; Ojibwe; Ojibwa",
	"ori": "ଓଡ଼ିଆ",
	"orm": "Afaan Oromoo",
	"osa": "Osage; Ohaebesha",
	"oss": "ирон; ирон æвзаг",
	"ota": "لسجن اوتومانى; Osmanlıca",
	"oto": "",
	"paa": "",
	"pag": "Pangasinan",
	"pal": "پهلوانی",
	"pam": "Fánggá'lehóng",
	"pan": "ਪੰਜਾਬੀ",
	"pap": "Papiamento",
	"pau": "Belau Llau; Tadai; Palauan; Belauan; Palauan Kelechek; Belauan Blai; Belauan Llau",
	"peo": "pārsi; pārsik; fārsi; fārsik; pārsik; ztf's; ztf'syn; pārsik; pārsik; pārsik; frsy; pārsik",
	"per": "فارسی",
	"phi": "",
	"phn": "𐤀𐤍𐤁𐤏𐤋; Phoenician; Phœnician",
	"pli": "पािल; Pāli; पािलि",
	"pol": "polski",
	"pon": "Pohnpeian; Pohnpei",
	"por": "português",
	"pra": "",
	"pro": "lenga d'òc; lenga d'òc (gascon); occitan",
	"pus": "پښتو",
	"que": "Runa Simi; Kichwa; Kichwa shimi; Kichwa runashimi; Runasimi; Runakuna; Runakuna; rúnasimi; rúnakuna; rúnakuna; rúnasimi; rúnasimi; rúnasimi; rúnasimi; rúnasimi; rúnakuna; rúnakuna; rúnasimi; rúnasimi; rúnasimi",
	"raj": "Rājasthānī",
	"rap": "",
	"rar": "Māori Kūki 'Āirani",
	"roa": "",
	"roh": "rumantsch grischun",
	"rom": "romani chib",
	"ron": "română",
	"rum": "română",
	"run": "Ikirundi; Kirundi",
	"rup": "Armãneashce; Lengua Armãneashti",
	"rus": "русский язык",
	"sad": "Kisandawi; Sándawe; Síndhaawé; Sindáwe; Sindáwi; Cindawe; CiNdaawé; Sídau; Cindawé; Cíndaawe; Síndhau; CiNdaawé; Sídau; Cindawé; Cíndaawe; Síndhau; Cindawé; Sídau; Cindawé; Cíndaawe; Síndhau",
	"sag": "yâpi chɔrɔ; yâpin mele; yâpin këri; yâpin mele n mele",
	"sah": "Сахалыы",
	"sai": "",
	"sal": "",
		"sam": "ארמית",
	"san": "संस्कृतम्",
	"sas": "",
	"sat": "ᱥᱟᱱᱛᱟᱲᱤ",
	"scn": "Sicilianu",
	"sco": "Braid Scots; Lallans",
	"sel": "",
	"sem": "",
	"sga": "Goídelc",
	"sgn": "",
	"shn": "Schrift လိၵ်ႈတႆ (lik tai) Sprache ၵႂၢမ်းတႆ (kwam tai)",
	"sid": "Sidaamu Afoo",
	"sin": "සිංහල",
	"sio": "",
	"sit": "",
	"sla": "",
	"slo* / slk": "slovenčina; slovenský jazyk",
	"slk / slo*": "slovenčina; slovenský jazyk",
	"slv": "slovenski jezik; slovenščina",
	"sma": "Åarjelsaemien gïele",
	"sme": "davvisámegiella",
	"smi": "",
	"smj": "julevsámegiella",
	"smn": "anarâškielâ",
	"smo": "Gagana faʻa Sāmoa",
	"sms": "sääʹmǩiõll",
	"sna": "chiShona",
	"snd": "सिन्धी,سنڌي، سندھی",
	"snk": "Sooninkanxanne",
	"sog": "",
	"som": "af Soomaali",
	"son": "",
	"sot": "Sesotho [southern]",
	"spa": "español; castellano",
	"sqi / alb*": "Shqip",
	"srd": "sardu; limba sarda; lingua sarda",
	"srn": "",
	"srp": "српски, srpski",
	"srr": "Seereer",
	"ssa": "",
	"ssw": "siSwati",
	"suk": "Kɪsukuma",
	"sun": "ᮘᮞ ᮞᮥᮔ᮪ᮓ, Basa Sunda",
	"sus": "Sosoxui",
	"sux": "𒅴𒂠",
	"swa": "Kiswahili",
	"swe": "svenska",
	"syc": "",
	"syr": "ܠܫܢܐ ܣܘܪܝܝܐ",
	"tah": "Reo Tahiti; Reo Mā'ohi",
	"tai": "ภาษาไท; ภาษาไต; ກຸ່ມພາສາໄຕ; ၵႂၢမ်းတႆ",
	"tam": "தமிழ்",
	"tat": "татар теле, tatar tele,تاتار",
	"tel": "తెలుగు",
	"tem": "KʌThemnɛ",
	"ter": "Terêna",
	"tet": "Lia-Tetun",
	"tgk": "тоҷикӣ, toçikī,تاجیکی",
	"tgl": "Wikang Tagalog",
	"tha": "ภษาไทย",
	"tib* / bod": "བོད་སྐད་; ལྷ་སའི་སྐད་",
	"tig": "ትግረ; ትግሬ; ኻሳ; ትግራይት",
	"tir": "ትግርኛ",
	"tiv": "",
	"tkl": "",
	"tlh": "",
	"tli": "Lingít",
	"tmh": "ⵜⴰⵎⴰⵌⴰⵆ",
	"tog": "chiTonga",
	"ton": "lea faka-Tonga",
	"tpi": "",
	"tsi": "",
	"tsn": "Setswana",
	"tso": "Xitsonga",
	"tuk": "Türkmençe, Түркменче, türkmen dili, түркмен дили,تورکمن تیلی, تورکمنچه",
	"tum": "chiTumbuka",
	"tup": "",
	"tur": "Türkçe",
	"tut": "",
	"tvl": "Te Ggana Tuuvalu; Te Gagana Tuuvalu",
	"twi": "",
	"tyv": "тыва дыл",
	"udm": "удмурт кыл",
	"uga": "",
	"uig": "Uyghurche,ئۇيغۇرچە",
	"ukr": "українська мова",
	"umb": "Úmbúndú",
	"und": "",
	"urd": "اردو",
	"uzb": "Oʻzbek, Ўзбек,أۇزبېك",
	"vai": "ꕙꔤ",
	"ven": "Tshivenḓa",
	"vie": "Tiếng Việt",
	"vol": "",
	"vot": "vađđa ceeli",
	"wak": "",
	"wal": "",
	"war": "Winaray; Samareño; Lineyte-Samarnon; Binisayâ nga Winaray; Binisayâ nga Samar-Leyte; “Binisayâ nga Waray”",
	"was": "wá:šiw ʔítu",
	"wel* / cym": "Cymraeg; y Gymraeg",
	"wen": "Serbsce, Serbski",
	"wln": "Walon",
	"wol": "",
	"xal": "Хальмг келн, Xaľmg keln",
	"xho": "isiXhosa",
	"yao": "",
	"yap": "",
	"yid": "ייִדיש, יידיש; אידיש",
	"yor": "èdè Yorùbá",
	"ypk": "",
	"zap": "Diidxazá",
	"zbl": "",
	"zen": "Tuḍḍungiyya",
	"zgh": "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ",
	"zha": "Vahcuengh, 話僮",
	"zho / chi*": "中文; 汉语; 漢語",
	"znd": "",
	"zul": "isiZulu",
	"zun": "Shiwi'ma",
	"zxx": "",
	"zza": ""
	}

static func get_iso_639_2_codes_endonyms():
	return iso_639_2_language_endonyms
