extends Node2D

const iso_639_1_language_endonyms = {
	"aa": "Afaraf",
	"ab": "аҧсуа бызшәа (apçua byzš°a)",
	"ae": "𐬀𐬞𐬀𐬐𐬙𐬀 (Avestā)",
	"af": "Afrikaans",
	"ak": "Akan",
	"am": "አማርኛ (Amarəñña)",
	"an": "aragonés",
	"ar": "العربية (al-ʻarabīyah)",
	"as": "অসমীয়া (Ôxômiya)",
	"av": "авар мацӀ (avar maʬ)",
	"ay": "aymar aru",
	"az": "azərbaycan dili",
	"ba": "башҡорт теле (bašqort tele)",
	"be": "беларуская мова (belaruskaya mova)",
	"bg": "български (bǎlgarski)",
	"bh": "भोजपुरी (Bhojpuri)",
	"bi": "Bislama",
	"bn": "বাংলা (Bangla)",
	"bo": "བོད་ཡིག (Bod skad)",
	"br": "brezhoneg",
	"bs": "bosanski jezik",
	"ca": "català",
	"ce": "нохчийн мотт (noxčiyin mott)",
	"ch": "Chamoru",
	"co": "corsu",
	"cs": "čeština",
	"cu": "ѩзыкъ словѣньскъ (Iztočnik)",
	"cv": "чӑваш чӗлхи (čăvaš čĕlxi)",
	"cy": "Cymraeg",
	"da": "dansk",
	"de": "Deutsch",
	"dv": "ދިވެހި (Dhivehi)",
	"dz": "རྫོང་ཁ (Dzongkha)",
	"ee": "Eʋegbe",
	"el": "Ελληνικά (Ellīniká)",
	"en": "English",
	"eo": "Esperanto",
	"es": "español",
	"et": "eesti",
	"eu": "euskara",
	"fa": "فارسی (Fārsi)",
	"ff": "Pulaar-Fulfulde",
	"fi": "suomi",
	"fj": "Vosa Vakaviti",
	"fo": "føroyskt",
	"fr": "français",
	"fy": "Frysk",
	"ga": "Gaeilge",
	"gd": "Gàidhlig",
	"gl": "galego",
	"gn": "Guarani",
	"gu": "ગુજરાતી (Gujarātī)",
	"gv": "Gaelg",
	"ha": "هَوُسَ (Hausa)",
	"he": "עִבְרִית (Ivrit)",
	"hi": "हिन्दी (Hindi)",
	"ho": "Hiri Motu",
	"hr": "Hrvatski",
	"ht": "Kreyòl ayisyen",
	"hu": "magyar",
	"hy": "Հայերեն (Hayeren)",
	"hz": "Otsiherero",
	"ia": "Interlingua",
	"id": "Bahasa Indonesia",
	"ie": "Interlingue",
	"ig": "Asụsụ Igbo",
	"ii": "ꆇꉙ (Yi)",
	"ik": "Iñupiaq",
	"io": "Ido",
	"is": "íslenska",
	"it": "italiano",
	"iu": "ᐃᓄᒃᑎᑐᑦ (Inuktitut)",
	"ja": "日本語 (Nihongo)",
	"jv": "Basa Jawa",
	"ka": "ქართული (Kartuli)",
	"kg": "Kikongo",
	"ki": "Gĩkũyũ",
	"kj": "Kuanyama",
	"kk": "қазақ тілі (qazaq tili)",
	"kl": "Kalaallisut",
	"km": "ភាសាខ្មែរ (Phéasa Khmér)",
	"kn": "ಕನ್ನಡ (Kannada)",
	"ko": "한국어 (Hangugeo)",
	"kr": "Kanuri",
	"ks": "کٲشُر (Kāšur)",
	"ku": "Kurdî",
	"kv": "коми кыв (komi kyv)",
	"kw": "Kernewek",
	"ky": "Кыргызча (Qırğızča)",
	"la": "Latina",
	"lb": "Lëtzebuergesch",
	"lg": "Luganda",
	"li": "Limburgs",
	"ln": "lingála",
	"lo": "ພາສາລາເ (Phaasaa Lao)",
	"lt": "lietuvių kalba",
	"lu": "Kiluba",
	"lv": "Latviešu valoda",
	"mg": "Malagasy fiteny",
	"mh": "Kajin M̧ajeļ",
	"mi": "te reo Māori",
	"mk": "македонски јазик (makedonski jazik)",
	"ml": "മലയാളം (Malayalam)",
	"mn": "Монгол (Mongol)",
	"mr": "मराठी (Marāṭhī)",
	"ms": "Bahasa Malaysia",
	"mt": "Malti",
	"my": "ဗမာစာ (Burmese)",
	"na": "Ekakairũ Naoero",
	"nb": "Norsk bokmål",
	"nd": "isiNdebele",
	"ne": "नेपाली (Nepālī)",
	"ng": "Owambo",
	"nl": "Nederlands",
	"nn": "Norsk nynorsk",
	"no": "Norsk",
	"nr": "isindebele",
	"nv": "Diné bizaad",
	"ny": "chiCheŵa",
	"oc": "occitan",
	"oj": "Anishinaabemowin",
	"om": "Afaan Oromoo",
	"or": "ଓଡ଼ିଆ (Oriya)",
	"os": "Ирон æвзаг (Iron ævzag)",
	"pa": "ਪੰਜਾਬੀ (Punjabi)",
	"pi": "पाऴि (Pāḷi)",
	"pl": "polski",
	"ps": "پښتو (Pashto)",
	"pt": "português",
	"qu": "Runa Simi",
	"rm": "rumantsch grischun",
	"rn": "kiRundi",
	"ro": "română",
	"ru": "русский язык (russkiy yazyk)",
	"rw": "Kinyarwanda",
	"sa": "संस्कृतम् (Sanskrit)",
	"sc": "Sardu",
	"sd": "سنڌي (Sindhi)",
	"se": "Davvisámegiella",
	"sg": "Sängö",
	"si": "සිංහල (Sinhala)",
	"sk": "slovenčina",
	"sl": "slovenščina",
	"sm": "Gagana Fa'a Samoa",
	"sn": "chiShona",
	"so": "Soomaaliga",
	"sq": "Shqip",
	"sr": "српски језик (srpski jezik)",
	"ss": "SiSwati",
	"st": "Sesotho",
	"su": "Basa Sunda",
	"sv": "Svenska",
	"sw": "Kiswahili",
	"ta": "தமிழ் (Tamil)",
	"te": "తెలుగు (Telugu)",
	"tg": "тоҷикӣ (tojikī)",
	"th": "ไทย (Thai)",
	"ti": "ትግርኛ (Tigrinya)",
	"tk": "Türkmen",
	"tl": "Tagalog",
	"tn": "Setswana",
	"to": "faka Tonga",
	"tr": "Türkçe",
	"ts": "Xitsonga",
	"tt": "татар теле (tatar tele)",
	"tw": "Twi",
	"ty": "Reo Tahiti",
	"ug": "ئۇيغۇرچە (Uyghurche)",
	"uk": "українська мова (ukrajins'ka mova)",
	"ur": "اردو (Urdu)",
	"uz": "o'zbek tili",
	"ve": "Tshivenḓa",
	"vi": "Tiếng Việt",
	"vo": "Volapük",
	"wa": "Walon",
	"wo": "Wolof",
	"xh": "isiXhosa",
	"yi": "ייִדיש (Yiddish)",
	"yo": "Èdè Yorùbá",
	"za": "Saɯ cueŋƅ",
	"zh": "中文 (Zhōngwén)",
	"zu": "isiZulu"
	}

static func get_iso_639_1_codes_endonyms():
	return iso_639_1_language_endonyms
